services:
  app:
    build: 
      context: . 
      dockerfile: Dockerfile
    image: php:8.2-fpm
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - laravel_network
    environment:
      - PHP_EXTENSIONS=mysqli,pdo_mysql

  webserver:
    image: nginx:alpine
    container_name: laravel_web
    volumes:
      - ./:/var/www/html
     
    ports:
      - "8080:80"
    networks:
      - laravel_network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: laravel_db
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel_network
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: my-spotify-taste
      MYSQL_USER: admin 
      MYSQL_PASSWORD: myspotifytaste

networks:
  laravel_network:

volumes:
  dbdata:
